### ISSUE TITLE
Bank Transfer Response Status

### ISSUE THREAD

**Issue by iyansanjaya** [ipaymu/iPaymu-WP-WooCommerce-Plugin#1]
Ketika pembayaran sudah dilakukan customer melalui bank transfer, status pembelian di WooCommerce tidak melakukan perubahan, sementara untuk QRIS berjalan dengan baik.

**Comment by raihan79c** [comment]
Apakah bug ini sudah di fix?

**Comment by iyansanjaya** [comment]
> Apakah bug ini sudah di fix?

kurang tau, karena waktu itu terlalu lama tidak ada perubahan, jadi saya ganti ke payment gateway lain yang lebih memperhatikan produk mereka.

**Comment by putuedi** [comment]
halo @iyansanjaya , 
mohon maaf sebelumnya, untuk hal tersebut bisa dicoba kembali.
untuk mendapatkan support lebih cepat bisa menghubungi support@ipaymu.com atau WhatsApp ke +62 819-3697-2473
