### ISSUE TITLE
incompatible feature 'High-Performance order storage'

### ISSUE THREAD

**Issue by qhoirulanwar** [ipaymu/iPaymu-WP-WooCommerce-Plugin#4]
detail message
This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage', it shouldn't be activated. 

installed on
wordpress version : 6.4.2
woocommerce version : 8.4.0

**Comment by ninonur** [comment]
tambah ini
`add_action('before_woocommerce_init', function(){

    if ( class_exists( \Automattic\WooCommerce\Utilities\FeaturesUtil::class ) ) {
        \Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'custom_order_tables', __FILE__, true );

    }

});`

**Comment by putuedi** [comment]
Hi @qhoirulanwar , 
We have updated the plugin, currently it doesn't support HPOS but it does support block checkout.
